// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okpsweljuzocapyvwlmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rcHN3ZWxqdXpvY2FweXZ3bG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzI4NTIsImV4cCI6MjA2OTIwODg1Mn0.lsnW2tCfNRjUD6Xn5kFINnI4tZoR7o2RwvOplhkuEeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});